# Enables or disables a desired property. Borrowed from std_srvs/SetBool until
# they release the package.

bool data
---
# Indicates whether the request was successful.
bool success

# Passes along the desired information, e.g. error messages.
string message
