# Sets the horizontal and vertical binning factors to get downsampled images.
# Binning refers to any camera setting which combines rectangular neighborhoods
# of pixels into larger 'super-pixels'. It reduces the resolution of the output
# image to (width / binning_x) x (height / binning_y). The default values
# binning_x = binning_y = 0 are considered the same as
# binning_x = binning_y = 1 (no subsampling).
uint32 target_binning_x
uint32 target_binning_y
---
# The reached binning factors may not always match the desired binning factors.
uint32 reached_binning_x
uint32 reached_binning_y
bool success