# Sets camera exposure time to the target exposure, given in microseconds. If
# camera limits are exceeded, exposure time will be set to one of those limits.
float32 target_exposure
---
# The reached exposure time may not exactly match the target exposure time.
float32 reached_exposure
bool success