# Sets the target gain as a percent of the maximum gain value the camera
# supports For USB cameras, the gain is given in dB. For GigE cameras it is
# given in so-called 'device specific units'.
float32 target_gain
---
# The reached gain main not exactly match the desired gain.
float32 reached_gain
bool success