# Sets the desired region of interest (ROI) to get a cropped image. The ROI is
# defined by the following four parameters: width, height, x_offset, and
# y_offset. The resulting cropped image will be of the form
# [x_offset : x_offset + width, y_offset : y_offset + height]. As such, the
# horizontal offset cannot be greater than the difference between image width
# and ROI width. Similarly, the vertical offset cannot be greater than the
# difference between image height and ROI height.
sensor_msgs/RegionOfInterest target_roi
---
# The reached ROI may not always match the desired ROI.
sensor_msgs/RegionOfInterest reached_roi
bool success